//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Graph.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_GRAPH                       3
#define IDS_YEAR                        50
#define IDS_PRINCIPAL                   51
#define IDS_INTEREST                    52
#define IDS_BALANCE                     53
#define IDI_GRAPH                       101
#define IDM_MENU                        102
#define APP_ICON                        102
#define IDD_ABOUTBOX                    103
#define IDD_LOANINFO                    104
#define CHECKBOX1                       111
#define CHECKBOX0                       112
#define RADIOBOX0                       113
#define RADIOBOX1                       114
#define IDB_BACKGROUND                  121
#define IDB_TOOLBAR                     122
#define IDD_LOANENTER                   123
#define IDD_LOANFORM                    123
#define IDD_LOANCALC                    124
#define IDD_CALC                        124
#define IDD_CALCULATOR                  124
#define IDD_WAVESHAPER                  125
#define IDC_CURSOR1                     126
#define IDD_CONVERSION                  126
#define IDD_TABLEEQUIVALENTS            127
#define IDD_TABLEEQUIV                  127
#define IDD_TEXTWINDOW                  127
#define IDD_EFFECTS                     128
#define IDD_DATAPLOTTER                 129
#define IDB_LEFT                        130
#define IDB_RIGHT                       131
#define IDB_CALCICON                    132
#define IDB_LOANICON                    133
#define IDB_WAVESHAPER                  134
#define IDB_CONVERSION                  135
#define IDM_MAIN_MENUITEM1              401
#define IDM_MAIN_MENUITEM2              402
#define IDM_MAIN_MENUITEM3              403
#define IDM_MAIN_MENUITEM4              404
#define IDS_MAIN_MENUITEM1              411
#define IDS_MAIN_MENUITEM2              412
#define IDS_MAIN_MENUITEM3              413
#define IDS_MAIN_MENUITEM4              414
#define IDM_MAIN_MENU                   450
#define IDM_LOANFORM_MENU               451
#define IDM_CALC_MENU                   452
#define IDM_LOANINFO_MENU               453
#define IDM_WAVESHAPER                  454
#define IDM_WAVESHAPE_MENU              454
#define IDM_CONVERSION_MENU             455
#define IDM_SIMPLE_MENU                 456
#define IDM_SIMPLEST_MENU               457
#define IDM_LOANINFO_EXIT               458
#define IDM_DATAPLOTTER_MENU            458
#define IDC_PROPERTYCOST                500
#define IDC_INTERESTRATE                501
#define IDC_YEARS                       502
#define IDC_LOANPAYMENT                 503
#define IDC_ADDTLPYMT                   504
#define IDC_LOANPAYMENT2                505
#define IDC_MONTHLYPAYMENT              505
#define IDC_LOANTITLE                   506
#define IDC_NEXT                        507
#define IDC_TOTALINTEREST               507
#define IDC_MORTGAGEAMT                 507
#define IDC_PREVIOUS                    508
#define IDC_ORIGFEE                     508
#define IDC_LOANDATE                    508
#define IDC_CALC0                       509
#define IDC_CALC1                       510
#define IDC_PMI                         510
#define IDC_CALC2                       511
#define IDC_ANNUALINS                   511
#define IDC_CALC3                       512
#define IDC_ANNUALTAX                   512
#define IDC_CALC4                       513
#define IDC_CALC5                       514
#define IDC_CALC6                       515
#define IDC_CALC7                       516
#define IDC_CALC8                       517
#define IDC_CALC9                       518
#define IDC_CALCPLUS                    519
#define IDC_CALCMINUS                   520
#define IDC_CALCMULT                    521
#define IDC_CALCDIV                     522
#define IDC_CALCCLEAR                   523
#define IDC_CALCBS                      524
#define IDC_CALCMEMPLUS                 525
#define IDC_CALCMEMMINUS                526
#define IDC_CALCMEMRETRIEVE             527
#define IDC_CALCMEMCLEAR                528
#define IDC_CALCEQUALS                  529
#define IDC_CALCPLUSMINUS               530
#define IDC_CALCRIGHTSHIFT              531
#define IDC_CALCLEFTSHIFT               532
#define IDC_CALCA                       533
#define IDC_CALCB                       534
#define IDC_CALCC                       535
#define IDC_CALCD                       536
#define IDC_CALCE                       537
#define IDC_CALCF                       538
#define IDC_CALCPOINT                   539
#define IDC_CALCCE                      540
#define IDC_CALCAND                     541
#define IDC_CALCOR                      542
#define IDC_CALCXOR                     543
#define IDC_CALCDEC                     544
#define IDC_CALCHEX                     545
#define IDC_CALCBIN                     546
#define IDC_CALCOCT                     547
#define IDC_CALCMOD                     548
#define IDC_CALCSQRT                    549
#define IDC_CALCSIN                     551
#define IDC_CALCCOS                     552
#define IDC_CALCTAN                     553
#define IDC_CALCASIN                    554
#define IDC_CALCATAN                    555
#define IDC_CALCACOS                    556
#define IDC_CALCLOAN                    557
#define IDC_CALCLCD                     1001
#define ID_STATIC                       1002
#define IDC_WAVECYCLES                  1002
#define IDC_WAVEPHASE                   1003
#define IDC_WAVERES                     1004
#define IDC_LEFT                        1005
#define IDC_WAVEOPCHOICE                1005
#define IDC_SIN01                       1010
#define IDC_COS01                       1011
#define IDC_TAN                         1012
#define IDC_COMBO1                      1022
#define IDC_SIN2                        1025
#define IDC_COS2                        1026
#define IDC_TAN2                        1027
#define IDC_COMBO2                      1028
#define IDC_COMBO3                      1029
#define IDC_CONV_INPUT1                 1033
#define IDC_CONV_INPUT2                 1034
#define IDC_CONV_UNITTYPE               1035
#define IDC_CONV_UNIT1                  1036
#define IDC_CONV_UNIT2                  1037
#define IDC_SCROLLBAR3                  1039
#define IDC_WAVE_BANKNO                 1041
#define IDC_WAVE_HIDE                   1042
#define IDC_TABLEEQUTEXT                1043
#define IDC_WAVEAMPLITUDE               1044
#define IDC_WAVBANK1                    1045
#define IDC_WAVBANK2                    1046
#define IDC_WAVBANK3                    1047
#define IDC_WAVBANK4                    1048
#define IDC_WAVBANK5                    1049
#define IDC_WAVBANK6                    1050
#define IDC_WAVBANK7                    1051
#define IDC_WAVBANK8                    1052
#define IDC_WAVESIN                     1053
#define IDC_WAVECOS                     1054
#define IDC_WAVETAN                     1055
#define IDC_WAVESSQU                    1056
#define IDC_WAVECSQU                    1057
#define IDC_WAVENSQU                    1058
#define IDC_WAVETRI                     1059
#define IDC_CHECK1                      1060
#define IDC_WAVESOM                     1060
#define IDC_WAVETSQU                    1061
#define IDC_WAVETANLIM                  1061
#define IDC_WAVEGRAPH                   1062
#define IDC_DEGRAD                      1063
#define IDC_CALCDEGRAD                  1064
#define IDC_MEMORY                      1065
#define IDC_CALCMEMORYLIGHT             1066
#define IDC_WAVEBANKTEXT                1067
#define IDC_LOANFORM_NEXTINFO           1068
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_HELP_NEW                    40004
#define IDM_LOAN_FORM                   40004
#define IDS_CAP_VIEW                    40006
#define IDS_CAP_EDIT                    40008
#define IDS_CAP_FILE                    40011
#define IDS_NEXT                        40017
#define IDS_PREVIOUS                    40019
#define IDS_CAP_CHOOSE                  40021
#define IDM_CALCULATOR                  40022
#define IDM_NEXT                        40023
#define IDM_PREVIOUS                    40024
#define IDM_LOAN_MENU1                  40026
#define IDS_CAP_APPS                    40028
#define IDS_CALC_SCHEDULER              40029
#define IDM_LOAN_NEXT                   40030
#define IDS_LOAN_NEXT                   40031
#define IDM_LOAN_PREVIOUS               40032
#define IDS_CAP_PREVIOUS                40034
#define IDS_CAP_NEXT                    40036
#define IDM_MAIN_EXIT                   40037
#define IDS_CAP_EXIT                    40039
#define IDM_GRAPH                       40041
#define IDS_CAP_CALC                    40044
#define IDM_CALC_EXIT                   40045
#define IDM_LOANFORM_EXIT               40047
#define IDS_CAP_PREV                    40057
#define IDM_LOANFORM_RESET              40059
#define IDS_CAP_RESET                   40060
#define IDM_CALC_LOAN                   40064
#define IDS_CAP_LOAN                    40066
#define IDM_CONVERSION                  40071
#define IDM_CONVERSION_EXIT             40072
#define IDM_WAVESHAPE_EXIT              40073
#define IDM_CONV_EXIT                   40074
#define IDM_MAIN_TABLES                 40075
#define IDM_TABLE_EQUIVALENTS           40076
#define IDM_MAIN_MENUITEM               40078
#define IDS_CAP_TABLES                  40080
#define IDM_SIMPLE_EXIT                 40081
#define IDM_SIMPLE_EDIT                 40082
#define IDS_CAP_WAVESHAPER              40086
#define IDM_SIMPLE_COPY                 40088
#define IDM_TABLE_FINANCIALS            40089
#define IDM_EFFECTS                     40090
#define IDM_WAVE_RESET                  40091
#define IDM_WAVESHAPERESET              40093
#define IDM_CALC_RESET                  40094
#define IDM_WAVESHAPEOPTIONS            40095
#define IDM_WAVEBANKX                   40097
#define IDM_WAVEBANK2                   40098
#define IDM_WAVEXVSY                    40098
#define IDM_WAVEBANKY                   40099
#define IDS_CAP_OPTIONS                 40101
#define IDM_LOANFORMOPTIONS             40102
#define IDM_AMORTIZEBYMONTH             40104
#define IDM_AMORTIZEBYYEAR              40105
#define IDM_LOANFORM_AMORTIZE           40108
#define IDS_CAP_AMORTIZE                40110
#define IDS_CAP_AMORTIZEBYMONTH         40113
#define IDS_CAP_AMORTIZEBYYEAR          40116
#define IDS_CAP_YEARLY                  40118
#define IDM_LOANINFO_MONTHLY            40119
#define IDM_LOANINFO_YEARLY             40120
#define IDM_WAVEPLAYX                   40121
#define IDM_WAVEPLAYY                   40122
#define IDM_WAVEPLAYXY                  40123
#define IDM_WAVESHAPESOUND              40124
#define IDS_CAP_SOUND                   40126
#define IDM_WAVEVOLLOUD                 40128
#define IDM_WAVEVOLMED                  40129
#define IDM_WAVEVOLSOFT                 40130
#define IDM_WAVEPRESETS                 40131
#define IDS_CAP_PRESETS                 40133
#define IDM_WAVEPREF001                 40140
#define IDM_WAVEPREF002                 40141
#define IDM_WAVEPREF003                 40142
#define IDM_WAVEPREF004                 40143
#define IDM_WAVEPREF005                 40144
#define IDM_WAVEPREF006                 40145
#define IDM_WAVEPREF007                 40146
#define IDM_WAVEPREF008					40147
#define IDM_WAVEPREF009					40148
#define IDM_DATAPLOTTER                 40152
#define IDM_DATAOPTIONS                 40153
#define IDM_DATANOTHING                 40156
#define IDM_DATAPLOTTER_EXIT            40157
#define IDM_TABLE_ASCII                 40159
#define IDM_WAVELIMITS                  40200
#define IDS_CAP_LIMITS                  40201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         40161
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
